name: Arqut Tunnel CE Service
description: Arqut Tunnel CE Service for Home Assistant
version: v0.1.2
slug: arqut-tunnel-ce-test
init: false
url: https://github.com/tphan267/arqut-ha-addon-ce
codenotary: tuan.phan267@gmail.com
webui: http://[HOST]:[PORT:3030]
image: ghcr.io/tphan267/arqut-edge-ce-ha-addon-{arch}
arch:
  - aarch64
  - amd64
  - armv7
  - i386
map:
  - type: homeassistant_config
    read_only: false
    path: /haconfig
startup: services
host_network: true
privileged:
  - NET_ADMIN
ports:
  3030/tcp: 3030
ports_description:
  3030/tcp: Used for web interface and API
options:
  edge_id: haaddon1
  api_key: ''
  server_url: ''
  data_dir: /data
  log_level: info
schema:
  edge_id: str
  api_key: str
  server_url: str
  data_dir: str
  log_level: list(error|warn|info|debug)
