name: Build Arqut Edge EE Binaries

on:
  workflow_call:
    inputs:
      # the version of binaries to build
      version:
        required: false
        description: "Tag or version to build (leave empty for latest tag)"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: "tphan267/arqut-edge-ee"
          token: ${{ secrets.WORKFLOW_PAT }}
          ref: main
          fetch-depth: 0
          fetch-tags: true

      - name: Checkout Tag (if version not empty)
        if: ${{ inputs.version != '' }}
        run: |
          git checkout ${{ inputs.version }}
      
      - name: Set release tag
        id: set_tag
        run: |
          if [ "${{ inputs.version }}" != "" ]; then
            echo "Using inputs tag: ${{ inputs.version }}"
            echo "tag_name=${{ inputs.version }}" >> $GITHUB_OUTPUT
          else
            git fetch --tags
            LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
            echo "Latest tag: $LATEST_TAG"
            echo "tag_name=$LATEST_TAG" >> $GITHUB_OUTPUT
          fi

      - name: Checkout Tag (if version not empty)
        if: ${{ steps.set_tag.outputs.tag_name != '' }}
        run: |
          git checkout ${{ steps.set_tag.outputs.tag_name }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.0.1"
          cache: "npm"
          cache-dependency-path: "ui/package-lock.json"

      - name: Build UI
        working-directory: ./ui
        run: |
          npm install
          npm run build

      - name: Build Binary with GoReleaser
        run: |
          set -e
          go version
          curl -sfL https://goreleaser.com/static/run | bash -s -- release --skip=announce,publish,validate --clean

          mkdir -p releases
          cp dist/arqut-edge-ee_linux_arm_7/arqut-edge-ee releases/arqut-edge-ee_linux-armv7
          cp dist/arqut-edge-ee_linux_arm_6/arqut-edge-ee releases/arqut-edge-ee_linux-armv6
          cp dist/arqut-edge-ee_linux_arm64_v8.0/arqut-edge-ee releases/arqut-edge-ee_linux-aarch64
          cp dist/arqut-edge-ee_linux_amd64_v1/arqut-edge-ee releases/arqut-edge-ee_linux-amd64
          cp dist/arqut-edge-ee_linux_386_sse2/arqut-edge-ee releases/arqut-edge-ee_linux-i386

          mkdir -p artifacts
          mv dist/arqut-edge-ee_linux_arm_7 artifacts/armv7
          mv dist/arqut-edge-ee_linux_arm_6 artifacts/armv6
          mv dist/arqut-edge-ee_linux_arm64_v8.0 artifacts/aarch64
          mv dist/arqut-edge-ee_linux_amd64_v1 artifacts/amd64
          mv dist/arqut-edge-ee_linux_386_sse2 artifacts/i386

      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: arqut-edge-ee-binaries
          path: artifacts/
          overwrite: true
          retention-days: 1